services:
  # Backend API Service
  - type: web
    name: feastfinder-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "3000"

  # Frontend Service
  - type: web
    name: feastfinder-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_BASE_URL
        value: https://feastfinder-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
